default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password: password
  host: 127.0.0.1
  port: 3307

development:
  <<: *default
  database: demurrage_development

test:
  <<: *default
  database: demurrage_test
